import random 
#● ┌ ─ ┐ │ └ ┘
#ASCII CODE
#u/25CF u/250C u/2500 u/2510 u/2502 u/2514
dice_art={
  
 1:     ("┌─────────┐",
         "│         │",
         "│    ●    │",
         "│         │",
         "└─────────┘" ),

 2:    ( "┌─────────┐",
         "│ ●       │",
         "│         │",
         "│       ● │",
         "└─────────┘" ),

 3:   (  "┌─────────┐",
         "│ ●       │",
         "│    ●    │",
         "│       ● │",
         "└─────────┘" ),

 4:   (  "┌─────────┐",
         "│ ●     ● │",
         "│         │",
         "│ ●     ● │",
         "└─────────┘" ),

5:    (  "┌─────────┐",
         "│ ●     ● │",
         "│    ●    │",
         "│ ●     ● │",
         "└─────────┘" ),

6:    (  "┌─────────┐",
         "│ ●     ● │",
         "│ ●     ● │",
         "│ ●     ● │",
         "└─────────┘" )
 }
dice=[]#random number generated by the ranfint will be stored here. the amount will be decided by the user in the num_of_die.
total=0 
num_of_dice=int(input("how many dice?: "))

for die in range(num_of_dice):#FOR CHOOSING RANDOM DICE BASED ON THE INPUT
 dice.append(random.randint(1, 6)) 

#for die in range(num_of_dice):           ]
 #for line in dice_art.get(dice[die]):    ] WILL GIVE THE dice_art in vertical 
  #print(line)                            ]

#for printing the output in horizontal fashion
for line in range(5): 
 for die in dice: 
  print(dice_art.get(die)[line], end=" ")
 print()   

for die in dice: 
 total+= die 

print(f"total: {total}") 